import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ChartColumnIncreasing } from "lucide-react";
import { ClerkProvider, SignedIn, SignedOut, SignInButton, SignUpButton } from "@clerk/nextjs";
import { Button } from "@/components/ui/button";
import UserDropdown from "./user.dropdown";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable} antialiased bg-background`}
        >
        <ThemeProvider 
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange>
          <nav className="bg-card text-card-foreground p-4 h-20 flex items-center justify-between">
          <Link href="/" className="font-bold text-2xl flex gap-1 items-center">
          <ChartColumnIncreasing className="text-lime-500" />CashFlowX
          </Link>
          <div className="flex items-center gap-3">
            <ModeToggle />
            <SignedOut>
              <div className="flex items-center">
                <Button asChild variant="link">
                  <SignInButton />
                </Button>
                <Button asChild variant="link">
                  <SignUpButton />
                </Button>
              </div>
            </SignedOut>
            <SignedIn>
              <UserDropdown />
            </SignedIn>
          </div>
          </nav>
        {children}
        <Toaster />
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
